django_multilang/django_multilang/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

urlpatterns += i18n_patterns(
    url(r'^', include('multilang.urls')),
)

django_multilang/multilang/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from . import views


app_name = 'multilang'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(_(r'^hello-world/'), views.greeting, name='greeting'),
]

django_multilang/multilang/models.py
from django.db import models

# Create your models here.

django_multilang/multilang/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'multilang/index.html')


def greeting(request):
    return render(request, 'multilang/greeting.html')

django_multilang/multilang/templates/multilang/greeting.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block content %}
  <h1>{% trans 'Hello world!' %}</h1>
  <a href="{% url 'multilang:index' %}">{% trans 'Main page' %}</a>
{% endblock %}

{% block scripts %}
{{ block.super }}
<!-- JS i18n support -->
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>

<script src="{% static 'js/add-text.js' %}"></script>
{% endblock %}

django_multilang/multilang/templates/multilang/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
  <h1>{% trans 'Welcome' %}</h1>
  <a href="{% url 'multilang:greeting' %}">{% trans 'Hello world!' %}</a>
{% endblock %}

django_multilang/templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <title>Django multilang</title>
  </head>

  <body>
    <nav>
      <div id="lang-selector">
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ redirect_to }}" />
          <input name="language" type="hidden" />
        </form>
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% for lang in LANGUAGES %}
          {% get_language_info for lang.0 as lang_info %}

          {% if lang_info.code == LANGUAGE_CODE %}
          <strong>{{ lang_info.name_local }}</strong>
          {% else %}
          <a href="{% url 'set_language' %}" class="setlang" data-code="{{ lang_info.code }}">{{ lang_info.name_local }}</a>
          {% endif %}

          {% if not forloop.last %}
          |
          {% endif %}
        {% endfor %}
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
            crossorigin="anonymous">
    </script>
    <script src="{% static 'js/set-language.js' %}"></script>
    {% endblock %}
  </body>
</html>